### ISSUE TITLE
Required feature - text to CAPITAL letters

### ISSUE THREAD

**Issue by githubcodemonkey** [githubcodemonkey/TextConverterApp#8]
Required feature - implement feature to convert to capital letters

**Comment by TheFirstMe** [comment]
Can I work on this?

**Comment by TheFirstMe** [comment]
@githubcodemonkey Is this meant to be a one-way conversion? Or should I also implement capital letters back to small letters?

**Comment by githubcodemonkey** [comment]
one way.. but perhaps create another pull request for text to lowercase.. and add as another page?

**Comment by TheFirstMe** [comment]
@githubcodemonkey Sure.
